CC = g++44

LIBROOT = $(PWD)/../hslib
HSNET_DIR = $(LIBROOT)/hs_net
HSNET_INCDIR = $(HSNET_DIR)/include
HSNET_LIBDIR = $(HSNET_DIR)/lib
HSDS_DIR = $(LIBROOT)/hs_ds
HSDS_INCDIR = $(HSDS_DIR)/include
HSDS_LIBDIR = $(HSDS_DIR)/lib

THIRDPARTY_DIR = $(PWD)/thirdparty
THIRDPARTY_INCDIR = $(THIRDPARTY_DIR)/include
THIRDPARTY_LIBDIR = $(THIRDPARTY_DIR)/lib
ZLOG_INCDIR = $(THIRDPARTY_INCDIR)/zlog
ZLOG_LIBDIR = $(THIRDPARTY_LIBDIR)/zlog
RAPIDJSON_INCDIR = $(THIRDPARTY_INCDIR)/rapidjson

COMMON_DIR = $(PWD)/common
COMMON_INCDIR = $(COMMON_DIR)
COMMON_SRCDIR = $(COMMON_DIR)
COMMON_OBJDIR = $(COMMON_DIR)/obj
COMMON_SRCS = $(COMMON_SRCDIR)/HsNetHandler.cpp \
			  $(COMMON_SRCDIR)/HsAgent.cpp
COMMON_OBJS = $(COMMON_OBJDIR)/HsNetHandler.o \
			  $(COMMON_OBJDIR)/HsAgent.o

UTILS_DIR = $(PWD)/utils
UTILS_INCDIR = $(UTILS_DIR)
UTILS_SRCDIR = $(UTILS_DIR)
UTILS_OBJDIR = $(UTILS_DIR)/obj
UTILS_SRCS = $(UTILS_SRCDIR)/hs_log.cpp
UTILS_OBJS = $(UTILS_OBJDIR)/hs_log.o

BIN_DIR = $(PWD)/bin
LOGINSERVER_BIN_DIR = $(BIN_DIR)/loginserver

LOGINSERVER_DIR = $(PWD)/loginserver
LOGINSERVER_INCDIR = $(LOGINSERVER_DIR)
LOGINSERVER_SRCDIR = $(LOGINSERVER_DIR)
LOGINSERVER_OBJDIR = $(LOGINSERVER_DIR)/obj

LOGINSERVER_TARGET = $(LOGINSERVER_BIN_DIR)/loginserver
LOGINSERVER_SRCS = $(LOGINSERVER_SRCDIR)/main.cpp \
				   $(LOGINSERVER_SRCDIR)/loginserver.cpp
LOGINSERVER_OBJS = $(LOGINSERVER_OBJDIR)/main.o \
				   $(LOGINSERVER_OBJDIR)/loginserver.o

CCLDFLAGS = -pthread -lrt -lm -Wl,--no-as-needed -ldl

all: init $(LOGINSERVER_TARGET) 

init:
	mkdir -p $(LOGINSERVER_OBJDIR)
	mkdir -p $(UTILS_OBJDIR)
	mkdir -p $(COMMON_OBJDIR)

$(COMMON_OBJS): $(COMMON_OBJDIR)/%.o: $(COMMON_SRCDIR)/%.cpp
	$(CC) -std=c++0x -c -fPIC -g $< -o $@ -I$(COMMON_INCDIR) -I$(HSNET_INCDIR)

$(UTILS_OBJS): $(UTILS_OBJDIR)/%.o: $(UTILS_SRCDIR)/%.cpp
	$(CC) -std=c++0x -c -fPIC -g $< -o $@ -I$(UTILS_INCDIR) -I $(ZLOG_INCDIR) -I $(THIRDPARTY_INCDIR)

$(LOGINSERVER_OBJS): $(LOGINSERVER_OBJDIR)/%.o: $(LOGINSERVER_SRCDIR)/%.cpp
	$(CC) -std=c++0x -c -fPIC -g $< -o $@ -I $(HSNET_INCDIR) -I $(HSDS_INCDIR) -I$(COMMON_INCDIR) -I $(UTILS_INCDIR) -I $(ZLOG_INCDIR) -I$(THIRDPARTY_INCDIR)

$(LOGINSERVER_TARGET): $(LOGINSERVER_OBJS) $(COMMON_OBJS) $(UTILS_OBJS)
	$(CC) -Wall -std=c++0x -o $(LOGINSERVER_TARGET) -g $(LOGINSERVER_OBJS) $(COMMON_OBJS) $(UTILS_OBJS) $(HSNET_LIBDIR)/hs_net.so $(HSDS_LIBDIR)/hs_ds.so $(ZLOG_LIBDIR)/libzlog.a $(CCLDFLAGS) 

.PHONY: clean

clean:
	rm -fr $(LOGINSERVER_OBJS) $(LOGINSERVER_TARGET) $(COMMON_OBJS) $(UTILS_OBJS)
